## Data Science Bootcamp Week 2 Assignment - October 15th 2024 

By: Liliana Pamasa

#### 1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [41]:
import numpy as np

a = np.array([3, 6, 9])
b = np.array([2,4, 6])
np.vstack((a,b))

array([[3, 6, 9],
       [2, 4, 6]])

In [42]:
np.hstack((a,b))

array([3, 6, 9, 2, 4, 6])

#### 2. Find common elements between A and B. [Hint : Intersection of two sets]

In [43]:
np.intersect1d(a,b)

array([6])

#### 3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [44]:
 nums = np.where((a > 3) & (a < 9))
a[nums]

array([6])

#### 4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [45]:
iris = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data' 

iris_2d = np.genfromtxt(iris, delimiter=',', dtype='float', usecols=[0,1,2,3])

filt = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(filt)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


#### Pandas Questions 5. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

In [60]:
import pandas as pd 
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#df.columns

filtered_df = df.loc[::20, 'Manufacturer':'Type']
filtered_df

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

#### 6. Replace missing values in Min.Price and Max.Price columns with their respective mean.

In [61]:
df['Min.Price']= df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price']= df['Max.Price'].fillna(df['Max.Price'].mean())
df.head(10)

Manufacturer       Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura     Integra    Small  12.900000   15.9  18.800000      25.0   
1          NaN      Legend  Midsize  29.200000   33.9  38.700000      18.0   
2         Audi          90  Compact  25.900000   29.1  32.300000      20.0   
3         Audi         100  Midsize  17.118605   37.7  44.600000      19.0   
4          BMW        535i  Midsize  17.118605   30.0  21.459091      22.0   
5        Buick     Century  Midsize  14.200000   15.7  17.300000      22.0   
6        Buick     LeSabre    Large  19.900000   20.8  21.459091      19.0   
7        Buick  Roadmaster    Large  22.600000   23.7  24.900000      16.0   
8        Buick     Riviera  Midsize  26.300000   26.3  26.300000      19.0   
9     Cadillac     DeVille    Large  33.000000   34.7  36.300000      16.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                 NaN      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   
5         31.0         Driver only        NaN  ...        6.0   189.0   
6         28.0         Driver only      Front  ...        6.0   200.0   
7         25.0         Driver only       Rear  ...        6.0   216.0   
8         27.0         Driver only      Front  ...        5.0   198.0   
9         25.0         Driver only      Front  ...        6.0   206.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   
5      105.0   69.0         41.0           28.0          16.0     NaN   
6      111.0   74.0         42.0           30.5          17.0  3470.0   
7      116.0   78.0         45.0           30.5          21.0  4105.0   
8      108.0    NaN         41.0           26.5          14.0  3495.0   
9      114.0   73.0         43.0           35.0          18.0  3620.0   

    Origin              Make  
0  non-USA     Acura Integra  
1  non-USA      Acura Legend  
2  non-USA           Audi 90  
3  non-USA          Audi 100  
4  non-USA          BMW 535i  
5      USA     Buick Century  
6      USA     Buick LeSabre  
7      USA  Buick Roadmaster  
8      USA     Buick Riviera  
9      USA  Cadillac DeVille  

[10 rows x 27 columns]

#### 7. How to get the rows of a dataframe with row sum > 100?

In [62]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# axis = 1 sets it to find the sum of rows 
filt_df = df[df.sum(axis=1) >100]

filt_df

0   1   2   3
0   26  21  36  21
3   29  32  33  39
5   16  34  18  35
6   29  10  29  33
7   35  26  31  35
9   34  28  34  34
14  31  37  22  16